// webreact/src/components/AppShell.jsx
import { useEffect, useMemo, useRef, useState } from "react";
import { Outlet, useLocation, useNavigate } from "react-router-dom";
import { Avatar, IconButton, SearchField } from "open-glass-ui";
import { getAssignments, getCourses } from "../data/api.js";
import { itemsOf } from "../data/contracts.js";
import { useApp } from "../app/AppContext.jsx";
import Iridescence from "./Iridescence.jsx";
import Prism from "./Prism.jsx";
import SmoothCursor from "./SmoothCursor.jsx";
import { Icon } from "./Icon.jsx";
import FloatingNav from "./FloatingNav/FloatingNav.jsx";
import LiquidMetalSurface from "./LiquidMetalSurface.jsx";
import { readStudyScene, STUDY_SCENE_ASSETS } from "../features/study/scenes.js";

const list = itemsOf;
const IRIDESCENCE_COLOR = Object.freeze([0.68, 0.78, 1]);

function SearchBox({ tone, disableEffects = false }) {
  const navigate = useNavigate();
  const [query, setQuery] = useState("");
  const [open, setOpen] = useState(false);
  const [results, setResults] = useState([]);
  const [loading, setLoading] = useState(false);
  const timer = useRef();
  useEffect(() => {
    if (query.trim().length < 2) { setResults([]); return undefined; }
    clearTimeout(timer.current);
    timer.current = setTimeout(async () => {
      setLoading(true);
      try {
        const [courses, assignments] = await Promise.all([getCourses(), getAssignments()]);
        const needle = query.trim().toLocaleLowerCase();
        const includes = (...values) => values.some((value) => String(value || "").toLocaleLowerCase().includes(needle));
        setResults([
          ...(list(courses).filter((item) => includes(item.name, item.code, item.semester)).map((item) => ({ title: item.name, detail: item.code || "课程详情", path: `/courses/${item.id}` }))),
          ...(list(assignments).filter((item) => includes(item.title, item.course_name, item.class_name)).map((item) => ({ title: item.title, detail: item.course_name || "课程作业", path: `/tasks/assignment/${item.id}` }))),
        ].slice(0, 8));
      } catch { setResults([]); } finally { setLoading(false); }
    }, 220);
    return () => clearTimeout(timer.current);
  }, [query]);
  const submitSearch = (event) => { if (event.key === "Enter" && query.trim()) { event.preventDefault(); navigate(`/home?q=${encodeURIComponent(query.trim())}`); setOpen(false); } };
  return <div className="search-wrap"><LiquidMetalSurface className="topbar-search-surface" contentClassName="topbar-search-metal-content" data-tone={tone} disableEffects={disableEffects} role="search" aria-label="全局搜索"><SearchField className="topbar-search" label="全局搜索" name="global-search" value={query} onFocus={() => setOpen(true)} onValueChange={(value) => { setQuery(value); setOpen(true); }} onKeyDown={submitSearch} placeholder="搜索课程、作业…" /><kbd className="topbar-search-shortcut">⌘ K</kbd></LiquidMetalSurface>{open && query.trim().length >= 2 && <div className="search-results" role="listbox">{loading ? <span>正在搜索…</span> : <>{results.map((item) => <button key={item.path} onClick={() => { navigate(item.path); setQuery(""); setOpen(false); }}><Icon name="PhArrowUpRight" size={15} /><span><strong>{item.title}</strong><small>{item.detail}</small></span></button>)}<button className="search-home-result" onClick={() => { navigate(`/home?q=${encodeURIComponent(query.trim())}`); setQuery(""); setOpen(false); }}><Icon name="PhMagnifyingGlass" size={15} /><span><strong>在首页筛选全部结果</strong><small>{query.trim()}</small></span></button></>}</div>}</div>;
}

export default function AppShell() {
  const { session, unreadCount, pendingCount, reduceMotion, dashboardStyle } = useApp();
  const location = useLocation();
  const navigate = useNavigate();
  const [systemReducedMotion, setSystemReducedMotion] = useState(() => window.matchMedia?.("(prefers-reduced-motion: reduce)")?.matches ?? false);
  const isHome = location.pathname === "/home";
  const isCourses = location.pathname.startsWith("/courses");
  const isCounselor = location.pathname.startsWith("/counselor");
  const isProfile = location.pathname === "/profile";
  const isStudy = ["/study", "/island", "/plans", "/docs", "/statistics"].some((route) => location.pathname === route || location.pathname.startsWith(`${route}/`));
  const [studyScene, setStudyScene] = useState(() => readStudyScene());
  const topbarGlassTone = isHome || isStudy || dashboardStyle === "gamified" ? "dark" : "light";
  const motionPaused = reduceMotion || systemReducedMotion;
  const today = useMemo(() => new Intl.DateTimeFormat("zh-CN", { month: "long", day: "numeric", weekday: "short" }).format(new Date()).replace("星期", "周"), []);
  const displayName = session?.name || session?.username || "同学";
  useEffect(() => { const onKey = (event) => { if ((event.ctrlKey || event.metaKey) && event.key.toLowerCase() === "k") { event.preventDefault(); document.querySelector('[name="global-search"]')?.focus(); } }; window.addEventListener("keydown", onKey); return () => window.removeEventListener("keydown", onKey); }, []);
  useEffect(() => {
    const mediaQuery = window.matchMedia?.("(prefers-reduced-motion: reduce)");
    if (!mediaQuery) return undefined;
    const syncMotionPreference = () => setSystemReducedMotion(mediaQuery.matches);
    mediaQuery.addEventListener?.("change", syncMotionPreference);
    return () => mediaQuery.removeEventListener?.("change", syncMotionPreference);
  }, []);
  useEffect(() => {
    const syncStudyScene = (event) => setStudyScene(event.detail || readStudyScene());
    window.addEventListener("campus-study-scene-change", syncStudyScene);
    return () => window.removeEventListener("campus-study-scene-change", syncStudyScene);
  }, []);
  const studyBackgroundStyle = isStudy ? { "--study-global-image": `url("${STUDY_SCENE_ASSETS[studyScene]}")` } : undefined;
  return <div style={studyBackgroundStyle} className={`app-layout ${isCourses ? "iridescence-background-active" : ""} ${isCounselor ? "counselor-mode" : ""} ${isProfile ? "profile-mode" : ""} ${isStudy ? "study-mode" : ""} ${reduceMotion ? "reduce-motion" : ""}`}>{isCourses && <Iridescence className="app-iridescence" color={IRIDESCENCE_COLOR} speed={0.38} amplitude={0.14} mouseReact={!motionPaused} paused={motionPaused} />}{isCounselor && <Prism className="app-counselor-prism" animationType="3drotate" timeScale={0.34} height={4.8} baseWidth={7.4} scale={2.2} hueShift={-0.12} colorFrequency={1.05} noise={0.012} glow={0.75} bloom={1.1} suspendWhenOffscreen={false} paused={motionPaused} />}{isProfile && <Prism className="app-profile-prism" animationType="3drotate" timeScale={0.2} height={4.3} baseWidth={5.8} scale={1.25} hueShift={0.1} colorFrequency={0.95} noise={0.008} glow={0.9} bloom={1.05} suspendWhenOffscreen={false} paused={motionPaused} />}{!isProfile && <SmoothCursor pointsCount={32} lineWidth={0.45} springStrength={0.38} dampening={0.52} color="var(--blue)" blur={3} mixBlendMode="screen" velocityScale trailOpacity={0.24} smoothFactor={1.4} paused={motionPaused} />}<a className="skip-link" href="#main-content">跳到主要内容</a>
    <div className="app-content"><header className="topbar"><SearchBox tone={topbarGlassTone} disableEffects={motionPaused} /><FloatingNav tone={topbarGlassTone} pendingCount={pendingCount} unreadCount={unreadCount} reduceMotion={motionPaused} /><LiquidMetalSurface className="topbar-info-surface" contentClassName="topbar-info-metal-content" data-tone={topbarGlassTone} disableEffects={motionPaused} role="group" aria-label="账户与通知"><div className="topbar-info"><span className="topbar-date">{today}</span><div className="topbar-actions"><IconButton className="topbar-notification" aria-label="通知" onClick={() => navigate("/notifications")}><Icon name="PhBell" size={18} /></IconButton><button className="topbar-account" aria-label="个人中心" onClick={() => navigate("/profile")}><Avatar name={displayName} src={session?.avatar_url || "/assets/generated/home-reference-student-avatar.png"} size="small" /><Icon name="PhCaretDown" size={14} /></button></div></div></LiquidMetalSurface></header><div className="route-stage"><Outlet /></div></div>
  </div>;
}

// web/src/views/AppShell.vue
<script setup>
import { computed, onMounted, onUnmounted, ref, watch } from "vue";
import { RouterView, useRoute, useRouter } from "vue-router";
import { useAppStore } from "../stores/app";
import UiIcon from "../components/UiIcon.vue";
import AppToastHost from "../components/AppToastHost.vue";
import AppConfirmHost from "../components/AppConfirmHost.vue";
import { getStudentAssignments, getStudentCourses } from "../services/studentApi";

const store = useAppStore();
const route = useRoute();
const router = useRouter();
const collapsed = ref(false);
const mobileOpen = ref(false);
const search = ref("");
const searchOpen = ref(false);
const searchResults = ref([]);
const searchLoading = ref(false);
let searchTimer;

const menus = [
  ["home", "首页", "PhHouse"],
  ["courses", "我的课程", "PhBookOpen"],
  ["community", "校园社区", "PhChatsCircle"],
  ["tasks", "待办与作业", "PhCheckSquare"],
  ["counselor", "AI 校园助手", "PhRobot"],
  ["notifications", "通知整理", "PhBell"],
  ["study", "学习陪伴", "PhChartLineUp"],
  ["profile", "个人中心", "PhUser"],
];

const todayLabel = computed(() => new Intl.DateTimeFormat("zh-CN", { month: "long", day: "numeric", weekday: "short" }).format(new Date()).replace("星期", "周"));
const profileRoute = computed(() => route.path === "/profile" || route.path.startsWith("/profile/"));
const profileDetail = computed(() => store.session?.detail || [store.session?.college, store.session?.major].filter(Boolean).join(" · ") || "信息工程学院 · 计算机科学与技术");

function go(path) {
  router.push(`/${path}`);
  mobileOpen.value = false;
}
function isActive(key) {
  const path = `/${key}`;
  return route.path === path || route.path.startsWith(`${path}/`);
}
function logout() {
  store.logout();
  router.replace("/login");
}
function openSearch() {
  searchOpen.value = true;
  requestAnimationFrame(() => document.querySelector('[name="global-search"]')?.focus());
}
function closeSearch() { searchOpen.value = false; }

async function runSearch() {
  const query = search.value.trim().toLocaleLowerCase();
  if (query.length < 2) { searchResults.value = []; searchLoading.value = false; return; }
  searchLoading.value = true;
  try {
    const [courseData, assignmentData] = await Promise.all([getStudentCourses(), getStudentAssignments()]);
    const includes = (...values) => values.some((value) => String(value || "").toLocaleLowerCase().includes(query));
    searchResults.value = [
      ...(courseData.items || []).filter((item) => includes(item.name, item.code, item.semester)).map((item) => ({ type: "课程", id: item.id, title: item.name, subtitle: item.code || item.semester || "课程详情", path: `/courses/${item.id}` })),
      ...(assignmentData.items || []).filter((item) => includes(item.title, item.course_name, item.class_name)).map((item) => ({ type: "作业", id: item.id, title: item.title, subtitle: item.course_name || item.class_name || "课程作业", path: `/tasks/assignment/${item.id}` })),
    ].slice(0, 8);
  } catch { searchResults.value = []; }
  finally { searchLoading.value = false; }
}
function chooseSearchResult(item) {
  router.push(item.path); search.value = ""; closeSearch();
}
function keydown(event) {
  if ((event.ctrlKey || event.metaKey) && event.key.toLowerCase() === "k") { event.preventDefault(); openSearch(); }
  if (event.key === "Escape") closeSearch();
}
watch(search, () => { searchOpen.value = true; clearTimeout(searchTimer); searchTimer = setTimeout(runSearch, 220); });
onMounted(() => window.addEventListener("keydown", keydown));
onUnmounted(() => { window.removeEventListener("keydown", keydown); clearTimeout(searchTimer); });
</script>

<template>
  <div class="app-layout student-layout" :class="{ collapsed, 'reduce-motion': store.reduceMotion, 'counselor-mode': route.path === '/counselor', 'study-mode': route.path === '/study' }">
    <AppToastHost /><AppConfirmHost />
    <button class="mobile-menu" aria-label="打开导航" @click="mobileOpen = true"><UiIcon name="PhList" /></button>
    <div v-if="mobileOpen" class="mobile-backdrop" @click="mobileOpen = false"></div>
    <aside class="sidebar" :class="{ open: mobileOpen }">
      <button class="profile-mini" :class="{ active: profileRoute }" @click="go('profile')">
        <span class="avatar"><img :src="store.session?.avatar_url || '/assets/generated/home-reference-student-avatar.png'" alt="" /></span>
        <span class="profile-mini-copy"><span class="profile-mini-name"><strong>{{ profileRoute ? "个人中心" : (store.session?.name || "陈同学(演示)") }}</strong><b v-if="!profileRoute">学生</b></span><small v-if="!profileRoute">{{ profileDetail }}</small></span>
        <UiIcon name="PhCaretRight" :size="16" />
      </button>
      <nav aria-label="主导航">
        <button v-for="[key, label, icon] in menus" :key="key" :class="{ active: isActive(key) }" :title="collapsed ? label : undefined" :aria-label="label" @click="go(key)">
          <UiIcon :name="icon" :size="20" /><span>{{ label }}</span><b v-if="key === 'tasks'">16</b><i v-if="key === 'notifications' && store.unreadCount" class="nav-dot"></i>
        </button>
      </nav>
      <div class="sidebar-bottom">
        <button title="收藏" aria-label="收藏" @click="go('profile/favorites')"><UiIcon name="PhBookmarkSimple" /><span>收藏</span></button>
        <button title="设置" aria-label="设置" @click="go('profile/settings')"><UiIcon name="PhGear" /><span>设置</span></button>
        <button :title="collapsed ? '展开导航' : '收起导航'" :aria-label="collapsed ? '展开导航' : '收起导航'" @click="collapsed = !collapsed"><UiIcon :name="collapsed ? 'PhCaretRight' : 'PhCaretLeft'" /><span>{{ collapsed ? "展开" : "收起" }}</span></button>
        <button title="退出登录" aria-label="退出登录" @click="logout"><UiIcon name="PhSignOut" /><span>退出登录</span></button>
      </div>
    </aside>
    <div class="workspace">
      <header class="topbar">
        <div class="command-search">
          <UiIcon name="PhMagnifyingGlass" :size="20" /><input v-model="search" name="global-search" placeholder="搜索课程或作业、通知、社区内容…" autocomplete="off" @focus="searchOpen = true" /><kbd>⌘ K</kbd>
        </div>
        <div class="top-date"><UiIcon name="PhCalendarBlank" :size="18" />{{ todayLabel }}</div>
        <div class="sync-pill" :class="{ offline: !store.backendOnline && route.path !== '/counselor' }"><UiIcon :name="store.backendOnline || route.path === '/counselor' ? 'PhCheckCircle' : 'PhCloudSlash'" :size="18" />{{ store.backendOnline || route.path === '/counselor' ? "已同步 · 刚刚" : "后端未连接" }}</div>
        <button class="icon-button notification-button" aria-label="通知" @click="go('notifications')"><UiIcon name="PhBell" :size="20" /><i></i></button>
      </header>
      <div v-if="searchOpen && search.length >= 2" class="global-search-panel">
        <div v-if="searchLoading" class="global-search-empty">正在搜索真实数据…</div>
        <div v-else-if="!searchResults.length" class="global-search-empty">没有匹配结果</div>
        <button v-for="item in searchResults" :key="`${item.type}-${item.id}`" @click="chooseSearchResult(item)"><span><strong>{{ item.title }}</strong><small>{{ item.type }} · {{ item.subtitle }}</small></span><UiIcon name="PhArrowRight" :size="15" /></button>
      </div>
      <RouterView :search-query="search" />
    </div>
  </div>
</template>
